
## Capstone Ideas

**Realtor**  
1. What is the problem you want to solve?   
A realtor wants to know which US city has the hottest market for selling a home. 

2. Who is your client and why do they care about this problem? In other words, what will your client DO or DECIDE based on your analysis that they wouldn't have otherwise?   
Realtors. A realtor may move to an area if they know they’ll have a greater chance at success.  

3. What data are you going to use for this? How will you acquire this data?   
Zillow Data (https://www.zillow.com/research/data/) broken down by city. Data sets:
Sold For Loss (%)
Sold For Gain (%)
Increasing Values (%)
Decreasing Values (%)
Listings With Price Cut (%)
Sold in the Past Year (%)
For-Sale Inventory (Raw)
Buyer-Seller Index
Market Health Index


4. In brief, outline your approach to solving this problem (knowing that this might change later).   
Determine the different definitions of success. 
- How quickly the houses sell? 
- Median home price?
- Are the houses more likely to sell over/under asking price?  
- What is the inventory of houses for sale?
- What is the potential of the area (buyer-seller, market health)? 

Combine the data sets. Clean up as the number of cities on the lists varies. Trend past 3 years. 

5. What are your deliverable?  
Code, along with a slide deck/visuals with insights and recommendations. 



--- ideas I'm not using ---


**Marketing Channels**   
1. What is the problem you want to solve? 
Which online marketing channels (or combination of channels) has the highest customer lifetime value. 

2. Who is your client and why do they care about this problem? In other words, what will your client DO or DECIDE based on your analysis that they wouldn't have otherwise? 
Client wants to optimize media spend and time investment in channels that will create the best long term value. 

3. What data are you going to use for this? How will you acquire this data? 
Internal data both online (Adobe and/or Google analytics) and potentially offline CRM data. 

4. In brief, outline your approach to solving this problem (knowing that this might change later). 
Find out which data sets I have access to. 
Determine how to stitch the data together (online, offline and media spend).
Start breaking down the channels with various attribution models and analyze which ones are the most profitable. 

5. What are your deliverable
Report published to github with R code as well as visuals. 


**Breastfeeding**  
1. What is the problem you want to solve? 
Mothers often stop breastfeeding for various reasons other than simply making a choice to stop. Often women would prefer to continue but stop due to various challenges.  If we can determine the major pain point(s) that lead to weaning, we can come up with proactive solutions to help mom continue breastfeeding. 

2. Who is your client and why do they care about this problem? In other words, what will your client DO or DECIDE based on your analysis that they wouldn't have otherwise? 
This information would be useful for all professionals who are involved with mom's who have recently had a baby. With this data, the client could proactively identify when a mom is close to feeling like she has to wean (when she would prefer not to).   

3. What data are you going to use for this? How will you acquire this data? 
https://www.cdc.gov/breastfeeding/index.htm 
https://www.cdc.gov/breastfeeding/data/reportcard.htm
https://www.cdc.gov/breastfeeding/data/ifps/data.htm 


4. In brief, outline your approach to solving this problem (knowing that this might change later). 
First identify main challenges women face when breastfeeding. 
Analyze various factors with support, number of children, type of delivery (c-section or vaginal), working outside the home, etc.
Look to see if certain challenges are more or less likely to influence weaning. 

5. What are your deliverable
Report published to github with R code as well as visuals. 
